import styled from 'styled-components';
import { ArrowDownRight, Plus } from 'lucide-react';
import type { Project } from '../../data/projects';
import { Tag } from '../atoms/Primitives';

const Card = styled.article<{ $featured: boolean }>`min-width: 0; grid-column: ${({ $featured }) => $featured ? '1 / -1' : 'auto'}; &:has(details[open]) { grid-column: 1 / -1; }`;
const Frame = styled.div`overflow: hidden; padding: 6px; background: #ff572d; margin-bottom: 24px; clip-path: polygon(0 3%,8% 1%,18% 3%,31% 0,48% 2%,62% 0,78% 2%,97% 0,100% 16%,98% 40%,100% 65%,98% 88%,100% 97%,83% 99%,65% 97%,45% 100%,28% 98%,10% 100%,0 96%,2% 72%,0 49%,2% 22%);`;
const Cover = styled.div<{ $web: boolean; $event: boolean }>`background: #101313; aspect-ratio: ${({ $event }) => $event ? '2.4' : '1.25'}; display: grid; grid-template-columns: ${({ $web, $event }) => $event ? 'repeat(3,1fr)' : $web ? '1fr 1fr' : '1fr'}; gap: 12px; padding: ${({ $web }) => $web ? '20px' : '12px'}; overflow: hidden; img { width: 100%; height: 100%; min-height: 0; object-fit: ${({ $web }) => $web ? 'cover' : 'contain'}; object-position: top; transition: transform .5s; } &:hover img { transform: translateY(-4px); } @media(max-width:600px) { aspect-ratio: ${({ $event }) => $event ? '1.2' : '1.25'}; grid-template-columns: ${({ $event, $web }) => $event || $web ? 'repeat(2,1fr)' : '1fr'}; ${({ $event }) => $event && 'img:nth-child(3) { display: none; }'} }`;
const Caption = styled.div`display: flex; justify-content: space-between; align-items: baseline; gap: 20px; margin-top: 16px; h3 { font-size: clamp(24px,3vw,34px); letter-spacing: -.045em; } span { font: 11px monospace; color: #a6a69e; }`;
const Description = styled.p`color: #b4b4ab; font-size: 14px; line-height: 1.7; margin-top: 12px;`;
const Details = styled.details`margin-top: 24px; border-top: 1px solid #ffffff30; summary { display: flex; align-items: center; justify-content: space-between; padding: 18px 0; cursor: pointer; font-size: 14px; font-weight: 700; list-style: none; color: #ff754e; } summary::-webkit-details-marker { display: none; } &[open] summary svg { transform: rotate(45deg); } summary svg { transition: transform .25s; }`;
const Case = styled.div`padding: 8px 0 24px; h4 { margin: 25px 0 10px; font-size: 17px; } p { font-size: 14px; line-height: 1.8; color: #b4b4ab; } .tags { display: flex; flex-wrap: wrap; gap: 8px; margin: 14px 0; } figure { margin: 28px 0 0; background: #242523; padding: 12px; } figcaption { color: #b4b4ab; font-size: 12px; line-height: 1.6; margin-top: 14px; } a { display: inline-flex; align-items: center; gap: 8px; font: 12px monospace; margin-top: 14px; color: #ff754e; }`;
const FullImage = styled.img<{ $portrait?: boolean }>`width: ${({ $portrait }) => $portrait ? 'auto' : '100%'}; max-width: 100%; height: auto; margin: auto;`;

const Gallery = styled.div<{ $event: boolean }>`display: grid; grid-template-columns: ${({ $event }) => $event ? 'repeat(3,1fr)' : '1fr'}; gap: 20px; align-items: start; @media(max-width:900px) { grid-template-columns: ${({ $event }) => $event ? 'repeat(2,1fr)' : '1fr'}; } @media(max-width:500px) { grid-template-columns: 1fr; }`;

export function ProjectCard({ project }: { project: Project }) {
  const web = project.preview === 'web';
  const event = project.preview === 'event';
  return <Card $featured={project.featured ?? event}><Frame><Cover $web={web} $event={event}>{web || event ? project.images.slice(0, event ? 3 : 2).map(image => <img key={image.src} src={image.src} alt={image.alt} loading="lazy"/>) : <img src={project.cover} alt={project.images[0].alt} loading="lazy"/>}</Cover></Frame><Tag>{project.category}</Tag><Caption><h3>{project.name}</h3><span>{project.id} /</span></Caption><Description>{project.description}</Description><Details><summary>Conheça o projeto <Plus size={20}/></summary><Case><h4>Objetivo</h4><p>{project.objective}</p><h4>Conceito & decisões visuais</h4><p>{project.concept}</p><h4>Técnicas utilizadas</h4><div className="tags">{project.techniques.map(technique => <Tag key={technique}>{technique}</Tag>)}</div><h4>{project.resultLabel ?? 'Resultado'}</h4><p>{project.result}</p><Gallery $event={event}>{project.images.map(image => <figure key={image.src}><FullImage src={image.src} alt={image.alt} $portrait={image.portrait} loading="lazy"/><figcaption>{image.caption}</figcaption><a href={image.src} target="_blank" rel="noreferrer">Abrir imagem original <ArrowDownRight size={15}/></a></figure>)}</Gallery></Case></Details></Card>;
}
