import styled, { keyframes } from 'styled-components';
import { ArrowUpRight, Mail, MessageCircle } from 'lucide-react';
import { Action, Container, Eyebrow, Tag } from '../atoms/Primitives';
import { ProjectCard } from '../molecules/ProjectCard';
import { projects } from '../../data/projects';
import { Artwork } from '../atoms/Artwork';
const slide = keyframes`to { transform: translateX(-50%); }`;
const Strip = styled.div`overflow: hidden; background: #ff572d; color: #181918; padding: 17px 0; margin-top: 0; .track { display: flex; width: max-content; animation: ${slide} 35s linear infinite; } span { font-weight: 800; font-size: 19px; text-transform: uppercase; padding: 0 25px; } &:hover .track { animation-play-state: paused; }`;
export function Marquee() { return <Strip aria-hidden="true"><div className="track">{Array.from({length: 4},(_,i)=><div key={i}><span>Identidade visual</span>✳<span>Ideias em movimento</span>✳<span>Experiências interativas</span>✳</div>)}</div></Strip>; }
const DarkSection = styled.section`padding: 95px 0;`;
const Heading = styled.div`display: flex; justify-content: space-between; gap: 30px; align-items: flex-end; margin: 24px 0 42px; h2 { font-size: clamp(40px,6vw,76px); letter-spacing: -.065em; line-height: .98; } p { max-width: 280px; color: #a6a69e; font-size: 14px; line-height: 1.6; } @media(max-width: 700px) { flex-direction: column; align-items: flex-start; }`;
const Grid = styled.div`display: grid; grid-template-columns: repeat(2,1fr); gap: 26px; @media(max-width: 800px) { grid-template-columns: 1fr; gap: 42px; }`;
export function Projects() { return <DarkSection id="projetos"><Container><Eyebrow>01 / Projetos</Eyebrow><Heading><h2>Projetos<br/><span style={{color: '#ff572d'}}>selecionados.</span></h2><p>Comunicação visual para diferentes marcas, públicos e formatos. Conheça as peças e as decisões por trás de cada conjunto.</p></Heading><Grid>{projects.map(project => <ProjectCard key={project.id} project={project}/>)}</Grid></Container></DarkSection>; }
const Paper = styled.section`background: #eeeae2; color: #181918; padding: 70px 0; background-image: url("/paper.svg");`;
const AboutGrid = styled.div`display: grid; grid-template-columns: 1.1fr 1fr .7fr; gap: 35px; align-items: center; h2 { font-size: clamp(42px,4.3vw,65px); line-height: .98; letter-spacing: -.065em; margin: 25px 0; } h2 span { color: #ff572d; } p { line-height: 1.8; font-size: 15px; max-width: 500px; } @media(max-width:800px) { grid-template-columns: 1fr; gap: 40px; }`;
const Skills = styled.div`border-top: 1px solid #18191840; > div { padding: 22px 0; border-bottom: 1px solid #18191840; display: flex; gap: 22px; } b { color: #ff572d; font: 12px monospace; padding-top: 6px; } h3 { font-size: 21px; letter-spacing: -.035em; margin-bottom: 8px; } p { font-size: 13px; color: #55564f; }`;
export function About() { return <Paper id="sobre"><Container><AboutGrid><div><Eyebrow>02 / Por trás das ideias</Eyebrow><h2>Criatividade<br/>em múltiplas<br/><span>formas.</span></h2><p>Sou Igor Moura, designer gráfico e game designer. Minha experiência conecta materiais de comunicação, identidade visual, animação e planejamento de jogos. Também exploro fotografia e desenvolvimento web.</p><p style={{marginTop: 18}}>De Recife para ideias que podem ir mais longe.</p></div><Artwork $scene="collage" role="img" aria-label="Colagem de fotografias de Recife e desenhos de personagens"/><Skills>{[['01','Design gráfico','Identidade visual, diagramação, infográficos e conteúdo para redes sociais.'],['02','Movimento','Animações e comunicação visual com Photoshop, Illustrator e After Effects.'],['03','Game design','Criatividade, mecânicas e narrativa para experiências interativas. Conceitos, sistemas de jogo e documentação de GDD com foco no jogador.']].map(([n,t,d])=><div key={n}><b>{n} /</b><div><h3>{t}</h3><p>{d}</p></div></div>)}</Skills></AboutGrid></Container></Paper>; }
const Timeline = styled.div`border-top: 1px solid #ffffff25; > div { display: grid; grid-template-columns: 1fr 1.4fr auto; gap: 30px; padding: 32px 0; border-bottom: 1px solid #ffffff25; } h3 { font-size: 23px; letter-spacing: -.03em; margin-bottom: 10px; } p { color: #a6a69e; font-size: 14px; line-height: 1.7; } time { font: 12px monospace; color: #a6a69e; } @media(max-width:700px) { > div { grid-template-columns: 1fr; gap: 15px; } }`;
export function Experience() { return <DarkSection id="experiencia"><Container><Eyebrow>03 / Trajetória</Eyebrow><Heading><h2>Ideias encontram<br/>experiência.</h2><Tag>DESIGN + TECNOLOGIA</Tag></Heading><Timeline><div><div><h3>Designer gráfico</h3><p>Grupo Ser Educacional</p></div><div><p>Desenvolvimento de peças gráficas e soluções visuais para diferentes demandas de comunicação institucional. Transformação de ideias, conceitos e informações em materiais estratégicos, considerando o público-alvo, os objetivos de cada projeto e a identidade visual da instituição.</p><p style={{marginTop: 14}}>Aplicação de composição visual, hierarquia da informação, tipografia, teoria das cores e tratamento de imagens para equilibrar criatividade, estética e funcionalidade. Atenção aos detalhes, consistência visual e adaptação aos diferentes formatos e canais de comunicação.</p></div><time>Ago. 2023 — Fev. 2026</time></div><div><div><h3>Game designer</h3><p>F12 Entertainment</p></div><div><p>Planejamento de conteúdo, dinâmicas e interações de jogos, com produção de documentação de GDD.</p><p style={{marginTop: 14}}>Meu processo conecta criatividade, estratégia e narrativa na concepção de conceitos, mecânicas e sistemas de jogo. Considero gameplay, progressão, desafios, ambientação e interação com o universo do jogo, buscando equilibrar diversão, funcionalidade e imersão.</p></div><time>Ago. 2022 — Ago. 2023</time></div></Timeline></Container></DarkSection>; }
const ContactBand = styled.section`background: #eeeae2 url("/paper.svg"); color: #181918; padding: 65px 0; h2 { font-size: clamp(53px,8vw,105px); line-height: .95; letter-spacing: -.065em; max-width: 900px; margin: 24px 0 35px; }`;
const ContactRow = styled.div`display: flex; align-items: center; flex-wrap: wrap; gap: 25px; p { font-size: 14px; }`;
const Footer = styled.footer`padding: 28px 0; > div { display: flex; justify-content: space-between; align-items: center; gap: 25px; flex-wrap: wrap; } p { font: 11px monospace; color: #a6a69e; } nav { display: flex; gap: 24px; font-size: 12px; } a { display: flex; align-items: center; gap: 4px; }`;
export function Contact() { return <><ContactBand id="contato"><Container><Eyebrow>04 / Próxima ideia</Eyebrow><h2>Vamos criar<br/>algo <span style={{color: '#ff572d'}}>juntos?</span></h2><ContactRow><Action href="mailto:igorms481@gmail.com">Vamos conversar <Mail size={19}/></Action><Action href="https://wa.me/5581982467134" target="_blank" rel="noopener noreferrer" aria-label="Conversar com Igor no WhatsApp (abre em nova aba)">Conversar no WhatsApp <MessageCircle size={19}/></Action><p>Aberto a conversar sobre design e novas oportunidades.</p></ContactRow></Container></ContactBand><Footer><Container><strong>IGOR MOURA<span style={{color:'#ff572d'}}> ↗</span></strong><p>RECIFE, PE · DESIGN & MOVIMENTO</p><nav><a href="https://www.behance.net/igormoura30" target="_blank" rel="noreferrer">Behance <ArrowUpRight size={14}/></a><a href="https://www.linkedin.com/in/igor-moura-7bb4221b4/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a><a href="/curriculo-igor-moura.pdf" target="_blank" rel="noreferrer">Currículo <ArrowUpRight size={14}/></a></nav></Container></Footer></>; }

const MotionBand = styled.section`background: #2348d1; padding: 60px 0; overflow: hidden; background-image: url('/paper.svg');`;
const MotionGrid = styled(Container)`display: grid; grid-template-columns: .85fr 1.3fr; gap: 60px; align-items: center; h2 { font-size: clamp(42px,5vw,70px); letter-spacing: -.065em; line-height: 1; margin: 25px 0; } h2 span { color: #ff572d; } p { font-size: 14px; line-height: 1.7; max-width: 320px; } @media(max-width:700px) { grid-template-columns: 1fr; gap: 35px; }`;
const moveType = keyframes`0%,100% { transform: translateX(-5px); } 50% { transform: translateX(12px); }`;
const Poster = styled.div`background: #181918 url('/paper.svg'); transform: rotate(-5deg); padding: 35px 30px; border: 10px solid #eeeae2; box-shadow: 15px 15px 0 #ff572d; position: relative; &::before { content: ''; width: 70px; height: 22px; background: #ff572dc9; position: absolute; top: -18px; left: 40%; transform: rotate(10deg); } p { font-size: clamp(45px,6vw,83px); font-weight: 950; line-height: .85; letter-spacing: -.06em; max-width: none; animation: ${moveType} 4s ease-in-out infinite; } p:nth-child(2) { color: #ff572d; animation-direction: reverse; } small { display: block; margin-top: 25px; font: 10px monospace; }`;
export function Motion() { return <MotionBand><MotionGrid><div><Eyebrow>Motion design</Eyebrow><h2>Movimento<br/>também<br/><span>comunica.</span></h2><p>Tipografia, ritmo e composição. Um espaço para apresentar animações e peças audiovisuais.</p></div><Poster aria-label="Estudo demonstrativo de tipografia animada"><p>IDEIAS</p><p>EM MOVI</p><p>MENTO.</p><small>ESTUDO TIPOGRÁFICO · CONCEITO ILUSTRATIVO</small></Poster></MotionGrid></MotionBand>; }
